# Generated by Django 4.0.4 on 2022-05-17 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitedWebPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('url_hash', models.CharField(editable=False, max_length=256)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('nb_http_link', models.PositiveIntegerField(default=0)),
                ('nb_tel_link', models.PositiveIntegerField(default=0)),
                ('nb_mail_link', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'visited_at',
                'index_together': {('url_hash', 'user')},
            },
        ),
    ]
